### ISSUE TITLE
Add info to README about how to make edits/add content to the website?

### ISSUE THREAD

**Issue by daattali** [STAT545-UBC/STAT545-UBC.github.io#20]
Not sure if you want to put this info in the README, but I just wanted to make a small edit to the people page but wasn't sure what the exact workflow is (I assume I just edit the markdown, render it to html, and add both the md and html files?)

**Comment by jennybc** [comment]
Yes. This is an example of something one of us could make nicer on the backend, i.e. add "edit this page" buttons and automate the knitting. But you're right a README is better than nothing.

**Comment by daattali** [comment]
I just updated some info about git but I only changed the markdown files, I did not add the html files because when I render them on my Windows machine it changes all the slashes and uses different bootstrap version. I *could* render all the html files and manually revert the lines that shouldn't be changed, but I'm hoping there's a better solution.

**Comment by jennybc** [comment]
As we just discussed in person, let's:

  * declare an official bootstrap version, make it very current, and require everyone to use it
    - [Migrating Websites to Bootstrap 3](http://rmarkdown.rstudio.com/html_document_format.html#creating-a-website)
  * make the windows people figure out this slash thing, i.e. fix it on their end

**Comment by daattali** [comment]
- I just created a new CSS style, I only added it to one page so you can see it and accept it before it goes live.  [here](http://stat545-ubc.github.io/block022_regular-expression.html).  Let me know if you want me to add that to the whole site (it only involves 2 line changes)

- I [filed an issue](https://github.com/rstudio/rmarkdown/issues/512) with rmarkdown regarding slashes so that I would be able to edit files 

- yes, that migration needs to happen, and then all the markdown files need to be re-rendered. It's not scary or too hard, but I can't do it because of my Windows issue

**Comment by jennybc** [comment]
Yes love the new CSS.

OK I will deal with the bootstrap thing while we let the slash issue play its course and someone, possible @ksamuk, determines how far we are from having a Makefile to re-render everything in an intelligent way, now and in future.

**Comment by ksamuk** [comment]
Also digging the new CSS! I will have a look into the Makefile stuff this evening/tomorrow morning. <famous last words> How hard can it be? </famous last words>. I'm also not super clear about how all naming conventions on the site fit together (e.g. the prefixes bit###_ and block###_, cm001_, etc.), but perhaps that will become apparent as I work through this!

**Comment by daattali** [comment]
So do I have the :+1: to go ahead and change the theme to this css across the site?

I just looked at [devtool's git hook](https://github.com/hadley/devtools/blob/master/inst/templates/readme-rmd-pre-commit.sh) and made this precommit hook that seems to work. You need to place it in a file `.git/hooks/pre-commit`

```
#!/bin/bash

# This is a pre-commit hook that checks for any HTML files that have corresponding
# md/rmd/Rmd files and ensures the HTML file is newer than its markdown

html_files=$(ls *.html)

for html_file in $html_files; do
    basename=${html_file%.html}
    md_files=$(find . -maxdepth 1 -regex "\./${basename}.[rR]?md")

    for md_file in $md_files; do
        if [[ $md_file -nt $html_file ]]; then
            echo "$html_file is out of date; please re-render it"
            exit 1
        fi
    done
done
```

@ksamuk sorry I took your job, just wanted to try it.. I'm not quite sure what the naming convention is with regards to bit vs block vs ???, but the general structure is: all webpages on the site are in the root directory of the project as a `.html` and have a corresponding `.md` file, while some also have a `.rmd` if they're more complex pages that include some code.  That's my understanding at least.

**Comment by jennybc** [comment]
Yes you have my blessing to recompile with better CSS and tell the rest of us what to do re: git precommit hook. How do you think this should relate to the bootstrap transition? And the slashes?

My filenaming convention:

  * block = a blob of content. The numbering is used to put in rough order of presentation. The slugs give info on what it is. These things can have a life outside of STAT545 but they are the main STAT545 content. I oftent use them in other workshops or link to them on twitter, etc.
  * cm: pertains specifically to STAT545 people meeting in person on a specific day. No primary content here. Just links to primary content, such as blocks or slides or external resources. Only interesting within the course.
  * bit: also a blob of content, but one that is possible outside the scope of STAT545. I should probably have a blog or website, but I don't need anything else to feel behind on. So when I feel like writing something up, I make it a bit and shove it into this repo.
  * Certan clumps of related blocks or bits have so many entries that they got their own nomenclature: e.g. automationXX, gitXX, packagesXX, shinyXX, webdataXX.

Clear as mud, yes?

**Comment by daattali** [comment]
I've done the necessary update, but only files that are re-rendered will be affected. We need to re-render all the files anyway when you do the switch to bootstrap 3, so I'd say just do all the rendering then.  This does not impact the bootstrap transition at all. Though beware that bootstrap 3 does have a different CSS so some things might look a bit different.

The slashes issue is independent of this as well. I'm just not going to render html files until that issue is fixed.

For the precommit hook: add a file named `.git/hooks/pre-commit` with the following content

```
#!/bin/bash

# This is a pre-commit hook that checks for any HTML files that have corresponding
# md/rmd/Rmd files and ensures the HTML file is newer than its markdown

html_files=$(ls *.html)

for html_file in $html_files; do
    basename=${html_file%.html}
    md_files=$(find . -maxdepth 1 -regex "\./${basename}.[rR]?md")

    for md_file in $md_files; do
        if [[ $md_file -nt $html_file ]]; then
            echo "$html_file is out of date; please re-render it"
            exit 1
        fi
    done
done
```

That's it.  Now whenever you try to commit it'll check for any html files, and for every html file it'll see if there are any md/rmd/Rmd files and if so then ensure the html file is newer. If not, it will tell you which file needs to be updated.


re: the bits: as I said on Twitter yesterday, you can make all those bits into a blog super easily if you want. I just took the liberty of doing that and [here you go](http://deanattali.com/jennybits/index.html) (it took quite literally 2 minutes).  I'll remove it later tonight because it's obviously not my content and it's hosted on my site, I just wanted to show you it can be very simple if you really cared :)

**Comment by jennybc** [comment]
I love the simulation of what my blog could look like. And yet ... I don't know if I need the pressure.

All looks great! Will do my parts re: upgrading bootstrap. Thanks for this.

**Comment by daattali** [comment]
official answer about the slash issue: [it is indeed a bug that wasn't know before, but they're reluctant to change it because it might break pandoc and it seems not worth it](https://github.com/rstudio/rmarkdown/issues/512)

so I'll just have to stick with manually reverting files, not too big of a deal

**Comment by jennybc** [comment]
I heard you were really good with git commit hooks. Why don't you write one to deal with the slashes? :smirk:

**Comment by ksamuk** [comment]
I'm new to using git hooks, but would it be possible to just use sed to switch the slashes? Could have a line in the for loop that does this? e.g.

```
#!/bin/bash

# This is a pre-commit hook that checks for any HTML files that have corresponding
# md/rmd/Rmd files and ensures the HTML file is newer than its markdown

html_files=$(ls *.html)

for html_file in $html_files; do
    basename=${html_file%.html}
    md_files=$(find . -maxdepth 1 -regex "\./${basename}.[rR]?md")

    for md_file in $md_files; do
        if [[ $md_file -nt $html_file ]]; then
            echo "$html_file is out of date; please re-render it"
            exit 1
        fi
    done
    # convert '\' to '/'
    sed 's/\\/\//g' $html_files > $html_files
done

```

**Comment by ksamuk** [comment]
Also re: the Makefile, I needed to do a little refresher on using make in R, which was fun! Installing make on my Windows machine was a breeze with the instructions posted on the website, so nice job whoever put those together.

For our application, Jenny mentioned the basic Makefile from the rmarkdown github repo, e.g.:

```
HTML_FILES := $(patsubst %.Rmd, %.html ,$(wildcard *.Rmd)) \
              $(patsubst %.md, %.html ,$(wildcard *.md))

all: clean html

html: $(HTML_FILES)

%.html: %.Rmd
	R --slave -e "set.seed(100);rmarkdown::render('$<')"

%.html: %.md
	R --slave -e "set.seed(100);rmarkdown::render('$<')"

.PHONY: clean
clean:
	$(RM) $(HTML_FILES)
```

Which merely wipes and re-render all the .Rmd files in the repo. What other functionality would we like to include in this?

**Comment by jennybc** [comment]
I think that's all we need. I just want to be able to say `make all` or `make web` and have any thing re-rendered where the md and/or html is less fresh than the Rmd or md. We need a `make clean; make web` workflow so when ... Dean changes the CSS, for example ... we can cause *everything* to be re-rendered. Probably also need a way -- possibly communicated via filename? -- to signal that something should only be rendered "by hand".

**Comment by daattali** [comment]
I think sed would be good to use for the slashes issue, but I wouldn't want
to simply convert all \ to / because \ can exist in other places in the
document that are unrelated. But yes that's the general idea

---
http://deanattali.com

**Comment by ksamuk** [comment]
Right, Option 1 above is the hammer-of-the-gods approach. Are there any other case were slashes need to be fixed? If no, maybe Option 2 above would do the trick, i.e. surgically edit that one specific string.

```
 # option 2: fix just that tag
    sed -i.bak 's,libs\\local\\nav.css,libs/local/nav.css,g' $html_file
    rm $html_file.bak
```

**Comment by jennybc** [comment]
Yihui just reminded me of this on twitter:

https://github.com/yihui/servr

Related to this discussion...

**Comment by jennybc** [comment]
The bootstrap transition is done. I rendered lots of stuff "by hand" but will await a more automated solution to do it *en masse*.

**Comment by ksamuk** [comment]
OK! I think I've worked out a Makefile that hits all the bases. Its pretty basic, so let me know what you guys think. See it here:

https://github.com/ksamuk/rmarkdown/blob/master/Makefile

Currently, it looks for all the html files that don't have the "_by_hand" prefix (which is a variable, so it can be set to whatever), and then renders them if they need to be updated (i.e. their Rmd/md is newer than they are, the default make behavior). All rendering and cleaning does not touch "by hand" files. 

In Rstudio, running "build all" will update non by-hand html files. Running "clean and rebuild" will nuke all the non by-hand html files and regenerate them.

I was just using a dummy repo at https://github.com/ksamuk/rmarkdown to try it out, which you could fork if you want to play around with this first. Let me know if it works for you guys!

**Comment by ksamuk** [comment]
One thing I couldn't figure out is how to run specific rules through Rstudio. It seems that its either run everything except for clean, or run clean and then everything. So if we wanted to have a rule that say, removed all the "_by_hand.html" files, I'm not sure how to do that. Perhaps just running make normally from the command line is the way around this.

**Comment by jennybc** [comment]
You are correct that only certain make targets are accessible via RStudio. Don't tell anyone but I have done some unholy things, like write a `clean` rule that's not exactly what the name suggests.

Yeah we should probably not do that but should go to the command line when necessary.

**Comment by ksamuk** [comment]
OK, that's what I suspected. Its strange that the `make` integration is so limited, but whatever!

So right now we have `make clean` and `make web`, and the "by hand" avoidance rules (although we'd need to decide on how to tag those files and change the `BY_HAND` variable accordingly). `all` currently just points to `web`, so perhaps it could be removed? 

Are there any other features we'd like? Otherwise I think this is ready to rock if you guys would like to experiment with it. I should note that I've just been testing this at home on my Windows machine.

**Comment by daattali** [comment]
So I hope people actually prefer the new look to the old one.  Does someone want to render all pages instead of us playing catchup and rendering one by one before each class? Or is there a reason we're not doing that?

**Comment by daattali** [comment]
Note: I updated the precommit hook (in [this comment above](https://github.com/STAT545-UBC/STAT545-UBC.github.io/issues/20#issuecomment-139450099)) to only look at staged files because I was getting errors when trying to commit because files that were not staged did not pass the check
