### ISSUE TITLE
Several of us did not receive the "invitation to STAT545 organization" Email

### ISSUE THREAD

**Issue by MaryHe** [STAT545-UBC/STAT545-UBC.github.io#24]
I did not receive the email mentioned in class (invitation to STAT545 organization?) And I asked several classmates, they did not receive either. Is this a common problem or just us? 

Thanks,
Mary

**Comment by jennybc** [comment]
It is a common problem and it's ME. Coming soon ....

**Comment by jennybc** [comment]
This should be done now. See https://github.com/STAT545-UBC/Discussion/issues/98.

For the future, a better place to open this issue is in our [Discussion repo](https://github.com/STAT545-UBC/Discussion/issues). This repository holds the content for the course website.
