### ISSUE TITLE
Mark homework 1 of Mary-He

### ISSUE THREAD

**Issue by MaryHe** [STAT545-UBC/STAT545-UBC.github.io#25]
@jennybc
38925929762c8f554efd34412b265803c347235f
https://github.com/STAT545-UBC/mary_he

**Comment by ksamuk** [comment]
Hi @MaryHe, the idea is for you to actually open these issues in your private repo, not here! So, please re-make the issue in your private repo.

**Comment by MaryHe** [comment]
Oops! Sorry, I just re-made the issue. Thanks!
