### ISSUE TITLE
add explicit LICENSE file

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/STAT545-UBC.github.io#26]
FYI there's already license info in the footer of all rendered pages but I should do this w/ explicit LICENSE file

**Comment by jennybc** [comment]
apparently it's not even the footer of index

**Comment by daattali** [comment]
It looks like the "this work is licensed under ..." will be default appear on all pages, but it's deliberately removed from several pages such as the homepage.  Was there any reason to purposely not include that footer on some pages? If not, that can be easily fixed

**Comment by jennybc** [comment]
I think it was an aesthetic choice? That I justifed in my mind because there really isn't any *content* to license on such a page? I don't feel strongly about this. I just want it to be clear people can reuse the stuff.
