### ISSUE TITLE
Shiny challenge: implement sthg like superheroes.talent-lab.com

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/STAT545-UBC.github.io#34]
tweet from @hrbrmstr

> superheroes.talent-lab.com (while !#rstats, still kinda cool). Perhaps a good student exercise to redo vis in R?

**Comment by jennybc** [comment]
how `bout a working link?

http://superheroes.talent-lab.com

**Comment by hrbrmstr** [comment]
To all of Dr. Bryan's students: My apologies for unwittingly creating extra work for you (but this shld be fun! mebbe? 😎)

**Comment by jennybc** [comment]
They have to create an app anyway, so anything less boring than more Gapminder is sweet relief for us all.
