### ISSUE TITLE
Buy a domain for the course site eg. http://stat545.com

### ISSUE THREAD

**Issue by daattali** [STAT545-UBC/STAT545-UBC.github.io#45]
(I thought I brought this up before, but I can't seem to find an issue about this)

STAT545 website is getting attention from all over the web.  It might be worth to spend the $15/year to have a nice domain for it that will make it much easier for students to remember the website, and also it'll give it a little bit more credibility.

After years of taking the course and being a TA, I still have to Google for the course every time I want to find it...

**Comment by jennybc** [comment]
Sure. Which extension is best you think? .com .org .ca ... ?

**Comment by daattali** [comment]
I'd say .com is easiest for people , and is the most commonly assumed default.  I personally use namecheap.com as my domain registrar, it's just $10/year, and it's super easy to get it to work with a jekyll website

**Comment by jennybc** [comment]
OK I am working on it (473ba3c0942d894ad6deebc6fe6b88af4dd4498d). Feel free to give instructions.

**Comment by jennybc** [comment]
I definitely managed to break everything. Currently waiting ~15 mins to see if I have also subsequently unbroken everything.

**Comment by daattali** [comment]
Breaking the site when the next class meeting is more than 5 hours away is small on you :)  Let me know if you need my help with anything.  Although, [stat545.com](http://stat545.com) seems to work for me so I think you're good? (It took me about 20 hours for my domain to work, so this was FAST!)

**Comment by daattali** [comment]
The Google Analytics settings might need to be updated, I'm not sure

**Comment by jennybc** [comment]
I appear to have unbroken things! 🎉

http://stat545.com

Will you look into whether we need to do anything re: Google Analytics? It can wait til after Friday's talk.

**Comment by daattali** [comment]
I changed the URL setting. The dplyr cheatsheet seems to be your star page :star:

**Comment by daattali** [comment]
Favicon is showing up now

**Comment by jennybc** [comment]
> The dplyr cheatsheet seems to be your star page

Make me feel even worse that it's so ugly 😔
