### ISSUE TITLE
oswald font not linked

### ISSUE THREAD

**Issue by stephenturner** [STAT545-UBC/STAT545-UBC.github.io#49]
In your navbar you're wanting Oswald, but not getting it.

```css
.nav li {
21	  font-family: 'Oswald', sans-serif;
```

**Comment by stephenturner** [comment]
might solve that by including the following in `include/in_header.html`

```html
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
```

**Comment by jennybc** [comment]
@daattali do you concur?

@stephenturner The navbar is something @daattali set up in the first place.

**Comment by daattali** [comment]
@stephenturner is right (how did you find that?!), adding that line would fix that. Though I don't know why that's the desired font to begin with (I git-blamed that line, it looks like it was done before I was even as a TA).  I just removed that font and we can keep using the sans-serif font we've always had

**Comment by stephenturner** [comment]
Oswald is thicker weight but narrower, makes for a nice navbar typeface if
you've got several headings. I actually liked it better on your site
template than the fallback sans-serif. I found it while tearing down the
css and other libs, transitioning to start using
http://rmarkdown.rstudio.com/rmarkdown_websites.html.
