### ISSUE TITLE
Make it clear to students that GitHub/git is not awesome for big files such as data files

### ISSUE THREAD

**Issue by daattali** [STAT545-UBC/STAT545-UBC.github.io#50]
This is an issue that just came up with @keshiniD.  In 545 we did a great job at getting students to join the "woo let's put our entire research project on github!" bandwagon, but we didn't really make it clear enough that data files and other really really big files should not go there.  Maybe mention it in the useR workshop as well?

**Comment by jennybc** [comment]
I know the actual rules but functionally, in practice, what is your personal definition of "big" here? At what size did you just experience pain? It also seems relevant whether the "big" files are changing or are static.

**Comment by daattali** [comment]
I'd say github rules (100mb/file) are good enough to use as the guideline of what not to commit.  There are two problems:
1. one is usability, that big files just suck with git
2. With files > 100MB, GitHub will say "no, you can't push this because the file is too large", but the problem is that this only happens *after* the file is git-committed. So you have a commit in your git history locally but github won't allow you to push it. IMO this is a common enough and PITA enough of a problem that it's worth mentioning, but if you don't think it is then that's fine, just wanted to get your opinion

**Comment by jennybc** [comment]
Sure I can mention. I guess I never expected someone to blithely commit 100+ MB files to a repo. It is "easy" enough to get it out of the local repo, especially you will not have pushed by definition (yes that's sarcasm, I know it's not "easy" to edit the history). But I take your point that it's always good to discuss what is appropriate for version control and what's not.
