### ISSUE TITLE
Link to Video about R reproducible workflow

### ISSUE THREAD

**Issue by scienceisfiction** [STAT545-UBC/STAT545-UBC.github.io#55]
I'm trying to sell friends and colleagues on this RStudio/GitHub workflow and wanted to share this video spoof on thriller/horror film trailers about improved workflow thanks to use of these tools. Here's the [link](https://www.youtube.com/watch?v=s3JldKoA0zw)!

**Comment by jennybc** [comment]
Yes! Thanks!

If you're willing play along ... I might title this "Link to video about R reproducible workflow" and describe like so ... "You played this awesome video in class on Sept 13 and I wanted to share w/ some colleagues, but I couldn't immediately find the link. Here it is: LINK. Would you add it to the slides and/or the class meetings notes?" 😄

Why?

It might not matter much in this case. But when issues might sit around for weeks or months,it's helpful if they are explicit, self-contained, and as timeless as possible.

Hey ... if you want to learn how to make a pull request and close this yourself, go to office hours this week and ask the TA to help you do it!
