### ISSUE TITLE
Broken link to HW10

### ISSUE THREAD

**Issue by dtavern** [STAT545-UBC/STAT545-UBC.github.io#59]
@jennybc 

Hi Jenny, there's a broken link on the [Tuesday/Thursday lecture](http://stat545.com/cm111_webdata.html) leading to the HW10 Assignment. It's giving me a 404. 

![broken_link](https://cloud.githubusercontent.com/assets/22035351/20844754/33e9e680-b876-11e6-8cc5-24305c5870ec.png)

**Comment by jennybc** [comment]
I think that may be an aspirational link because I still need to write up that homework .... 😰 will do today.
