### ISSUE TITLE
Encoding from Windows

### ISSUE THREAD

**Issue by gergness** [STAT545-UBC/STAT545-UBC.github.io#62]
I've been troubleshooting code that deals with non-english text that I run both on Windows and Linux. The encoding section (block032) here was a big help, but behaves differently when run on Windows as compared to Linux.

(Of course, there is a chance that this is all entirely specific to my setup, and not really Windows issues. If so, sorry!)

Full results of knitting from my windows machine: 
[block032_character-encoding.zip](https://github.com/STAT545-UBC/STAT545-UBC.github.io/files/1223343/block032_character-encoding.zip)

Issues:

1) Possibly would be good to mention that in RStudio, to open this Rmd file (and others with UTF-8 characters), windows users need to select "Reopen with encoding".

2) Encodings of the text characters read into R via the source code aren't always maintaining their UTF-8 encoding. My guess is that R in Windows is converting all characters that can be Latin1 to Latin1, regardless of how it's stored in the source code.

The first time this comes up in the Rmd is lines 87-91:

(Windows)
```r
string_latin <- iconv("hellÔ!", from = "UTF-8", to = "Latin1")
string_latin
#> [1] NA
charToRaw(string_latin)
#> [1] 4e 41
as.integer(charToRaw(string_latin))
#> [1] 78 65
```

(Linux)
```r
string_latin <- iconv("hellÔ!", from = "UTF-8", to = "Latin1")
string_latin
#> [1] "hell\xd4!"
charToRaw(string_latin)
#> [1] 68 65 6c 6c d4 21
as.integer(charToRaw(string_latin))
#> [1] 104 101 108 108 212  33
```

Similar issues in most of the other code blocks (though not line 63)

Further exploration:
(Windows)
```r
# Line 63 of Rmd (Works the same across platforms):
Encoding("hellṏ!")
#> [1] "UTF-8"

# Line 87 of Rmd (Windows decides it is already latin1):
Encoding("hellÔ!")
#> [1] "latin1"

# Only fix I've found is specify char using \u
"hell\u00d4!"
#> [1] "hellÔ!"
Encoding("hell\u00d4!")
#> [1] "UTF-8"

# Even specifying encoding in `source()` doesn't work...
temp_file <- tempfile()
readr::write_lines('utf_text <- "hell\u00d4!" \n Encoding(utf_text)', temp_file)
source(temp_file, encoding = "UTF-8", echo = TRUE)
#>> utf_text <- "hellÔ!"
#>
#>> Encoding(utf_text)
#>[1] "latin1"
```

3) When reverse encoding (in Encoding repair section), sometimes iconv doesn't return the encoding on the character vector returned, so you need to specify it on Windows or else it will continue to be treated as latin1.

I don't think this particular issue doesn't hit your "they're" -> "they're" example, but did on the file I was working with.

(Windows)
```r
(text <- "\u007b\u0050\u0072\u006f\u00c3\u00ad\u006e\u0063\u0069\u0061\u007d")
#> "{ProvÃ­ncia}"
(fixed <- iconv(text, from = "UTF-8", to = "Windows-1252"))
#> "{ProvÃ­ncia}"
Encoding(fixed)
#> "unknown"
Encoding(fixed) <- "UTF-8"
fixed
#> [1] "{Província}"
```

(Linux)
```r
(text <- "\u007b\u0050\u0072\u006f\u00c3\u00ad\u006e\u0063\u0069\u0061\u007d")
#> "{ProvÃ­ncia}"
(fixed <- iconv(text, from = "UTF-8", to = "Windows-1252"))
#> "{Província}"
Encoding(fixed)
#> "unknown"
Encoding(fixed) <- "UTF-8"
fixed
#> [1] "{Província}"
```

<details>
  <summary>Here's my Windows session info:</summary>
<pre>
devtools::session_info()
##  yaml        2.1.14  2016-11-12 CRAN (R 3.4.1)
</pre>
</details>

**Comment by jennybc** [comment]
Thanks! This is especially hard because, as you say, there are issues of which encoding is used when opening the file and then there's what knitr does 😔 to it. And it all interacts.

**Comment by jennybc** [comment]
Thanks for this! We're preparing to archive this repo:

  * The non-perishable STAT 545 content has (finally) been ported to bookdown and lives in a new repo: <https://help.github.com/en/articles/archiving-repositories>
  * Material specific to the UBC course and individual course runs:
    - Website: <https://stat545.stat.ubc.ca>
    - Repo: <https://github.com/STAT545-UBC/STAT545-home>

If you still care about this and you think something still needs attention, we'd love to hear from you at:

https://github.com/rstudio-education/stat545/issues
