### ISSUE TITLE
summarise_each() provided as example although function is deprecated

### ISSUE THREAD

**Issue by jmostipak** [STAT545-UBC/STAT545-UBC.github.io#67]
The text provides `summarise_each()` [as a method for applying summary functions to multiple variables](http://stat545.com/block010_dplyr-end-single-table.html), however when executed returns the error message that `summarise_each()` is deprecated.

**Comment by jennybc** [comment]
Do you want to have a go at this in a PR?

**Comment by JesseMostipak** [comment]
sure - happy to give it a go!

**Comment by jennybc** [comment]
Thanks for this! We're preparing to archive this repo:

  * The non-perishable STAT 545 content has (finally) been ported to bookdown and lives in a new repo: <https://help.github.com/en/articles/archiving-repositories>
  * Material specific to the UBC course and individual course runs:
    - Website: <https://stat545.stat.ubc.ca>
    - Repo: <https://github.com/STAT545-UBC/STAT545-home>

If you still care about this and you think something still needs attention, we'd love to hear from you at:

https://github.com/rstudio-education/stat545/issues
