### ISSUE TITLE
`summarise_each()` is deprecated

### ISSUE THREAD

**Issue by osborneo** [STAT545-UBC/STAT545-UBC.github.io#69]
Hi there, 
This is my first attempt at posting an issue and as a disclaimer I'm a complete  'R' beginner, so I'm apologizing in advance for any mistakes I'm making here.

I have a script I'm modifying to run on my computer (I didn't write it myself, it came as a supplement from an article) and I've run into a few problems, the first seems to be an error  `summarise_each()` is deprecated. Here is my code, followed by the error:
>library(dplyr)
>scales<-plotMultiScale1(all_tracks, radius, xmax = max(radius), Resti = 1.9)

`summarise_each()` is deprecated.
Use `summarise_all()`, `summarise_at()` or `summarise_if()` instead.
To map `funs` over a selection of variables, use `summarise_at()`
Error in combine_vars(vars, ind_list) : Position must be between 0 and n

Here is an example of "all_tracks" as printed out in the console: 
364             12.5102888          0.408184999           0.22795696    -0.1802280388          223.583333          12.5102888        0.408184999         0.22040897  -1.877760e-01
365             12.5102888          0.408184999           0.22795696    -0.1802280388          223.583333          12.5102888        0.408184999         0.22040897  -1.877760e-01
366             12.5102888          0.408184999           0.22795696    -0.1802280388          223.583333          12.5102888        0.408184999         0.22040897  -1.877760e-01
 [ reached getOption("max.print") -- omitted 3185 rows ]

And this is "radius" printed out:

[[2]]
 [1] 0.001 0.010 0.050 0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 1.000 1.100 1.200 1.300 1.400 1.500 1.600 1.700 1.800 1.900 2.000 2.100 2.200 2.300 2.400 2.500 2.600 2.700
[31] 2.800 2.900 3.000 3.100 3.200 3.300 3.400 3.500 3.600 3.700 3.800 3.900 4.000 4.100 4.200 4.300 4.400 4.500 4.600 4.700 4.800 4.900 5.000

I also get this message after running  >library(dplyr):

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

I hope that's enough information to go by, any assistance is greatly appreciated.

**Comment by jennybc** [comment]
Thanks for this! We're preparing to archive this repo:

  * The non-perishable STAT 545 content has (finally) been ported to bookdown and lives in a new repo: <https://help.github.com/en/articles/archiving-repositories>
  * Material specific to the UBC course and individual course runs:
    - Website: <https://stat545.stat.ubc.ca>
    - Repo: <https://github.com/STAT545-UBC/STAT545-home>

If you still care about this and you think something still needs attention, we'd love to hear from you at:

https://github.com/rstudio-education/stat545/issues
